apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  labels:
    app: postgres
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 200
    shared_buffers = 256MB
    work_mem = 4MB
    maintenance_work_mem = 64MB
    wal_level = replica
    logging_collector = on
    log_directory = '/mnt/postgresql-16/pglogs/logs'
    log_filename = 'postgresql-%Y-%m-%d.log'
  pg_hba.conf: |
    local   all             all                                   trust
    host    all             all             0.0.0.0/0               md5
